openapi: 3.0.0
info:
   title: Music API
   version: 1.0.0
paths: {}

components:
   schemas:
      Album:
         x-taxi-type:
            name: music.Album
         required:
            - title
            - artist
            - releaseYear
            - genre
         properties:
            title:
               x-taxi-type:
                  name: music.AlbumTitle
               type: string
            artist:
               x-taxi-type:
                  name: music.ArtistName
               type: string
            releaseYear:
               x-taxi-type:
                  name: music.ReleaseYear
               type: integer
               format: int32
            genre:
               x-taxi-type:
                  name: music.Genre
               type: string
